/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lspb.mapamanual;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
//import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTAtomOneDarkIJTheme;   o en su defecto los otros temas de personalizacion
//import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTAtomOneLightIJTheme;  o en su defecto los otros temas de personalizacion
import javax.swing.SwingUtilities;

/**
 *
 * @author santiago
 */
public class ConfiguracionMapa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfiguracionMapa.class.getName());

    /**
     * Creates new form ConfiguracionMapa
     */
    public ConfiguracionMapa() {
        initComponents();
        setLocationRelativeTo(null);
        if(FramePrincipal.necesarioRecargar){
            CheckSeguir.setSelected(true);
        }
        if(FramePrincipal.variosWaypoints){
            CheckMultiplesWaypoints.setSelected(true);
        }
        if(FramePrincipal.Tema==0){
            BtnClaro.setSelected(true);
        }else{
            BtnOscuro.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTemas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        CheckSeguir = new javax.swing.JCheckBox();
        CheckMultiplesWaypoints = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        BtnOk = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        BtnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnClaro = new javax.swing.JRadioButton();
        BtnOscuro = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración del Mapa");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Configuración adicional:");

        CheckSeguir.setText("Seguir al waypoint");

        CheckMultiplesWaypoints.setText("Permitir multiples waypoints");

        BtnOk.setText("Ok");
        BtnOk.addActionListener(this::BtnOkActionPerformed);

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(this::BtnCancelarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Tema:");

        GrupoTemas.add(BtnClaro);
        BtnClaro.setText("Claro");
        BtnClaro.addActionListener(this::BtnClaroActionPerformed);

        GrupoTemas.add(BtnOscuro);
        BtnOscuro.setText("Oscuro");
        BtnOscuro.addActionListener(this::BtnOscuroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CheckMultiplesWaypoints)
                            .addComponent(CheckSeguir))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnClaro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnOscuro))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckSeguir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckMultiplesWaypoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClaro)
                    .addComponent(BtnOscuro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOk)
                    .addComponent(BtnCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        FramePrincipal.necesarioRecargar = CheckSeguir.isSelected();
        FramePrincipal.variosWaypoints = CheckMultiplesWaypoints.isSelected();
        this.dispose();
    }//GEN-LAST:event_BtnOkActionPerformed

    private void BtnClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClaroActionPerformed
        FlatAnimatedLafChange.showSnapshot();

        // Programa el cambio para que ocurra después de que la UI haya terminado
        // sus tareas actuales
        SwingUtilities.invokeLater(() -> {
            // Establecer el nuevo tema
            FlatLightLaf.setup();
            // Forzar la actualización de toda la UI de la ventana principal
            SwingUtilities.updateComponentTreeUI(this);
            SwingUtilities.updateComponentTreeUI(FramePrincipal.Mapa); 
            // Iniciar la animación de desvanecimiento
            FlatAnimatedLafChange.hideSnapshotWithAnimation();
        });
        
        FramePrincipal.Tema=0;
    }//GEN-LAST:event_BtnClaroActionPerformed

    private void BtnOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOscuroActionPerformed
        FlatAnimatedLafChange.showSnapshot();

        // Programa el cambio para que ocurra después de que la UI haya terminado
        // sus tareas actuales
        SwingUtilities.invokeLater(() -> {
            // Establecer el nuevo tema
            FlatDarkLaf.setup();
            // Forzar la actualización de toda la UI de la ventana principal
            SwingUtilities.updateComponentTreeUI(this);
            SwingUtilities.updateComponentTreeUI(FramePrincipal.Mapa);
            // Iniciar la animación de desvanecimiento
            FlatAnimatedLafChange.hideSnapshotWithAnimation();
        });
        
        FramePrincipal.Tema=1;
    }//GEN-LAST:event_BtnOscuroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfiguracionMapa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JRadioButton BtnClaro;
    private javax.swing.JButton BtnOk;
    private javax.swing.JRadioButton BtnOscuro;
    private javax.swing.JCheckBox CheckMultiplesWaypoints;
    private javax.swing.JCheckBox CheckSeguir;
    private javax.swing.ButtonGroup GrupoTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
